---
# - name: Add Elasticsearch GPG key.
#   rpm_key:
#     key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
#     state: present

# - name: Add Logstash repository.
#   copy:
#     src: logstash.repo
#     dest: /etc/yum.repos.d/logstash.repo
#     mode: 0644

# - name: Install Logstash.
#   yum: pkg=logstash state=installed
# - name: Install Java
#   yum: pkg=java-1.7.0-openjdk* state=installed

- name: Copy logstash yum to remote
  copy: src=./logstash-2.3.4-1.noarch.rpm dest=/tmp/logstash-2.3.4-1.noarch.rpm

- name: RedHat - Install Logstash
  yum: name=/tmp/logstash-2.3.4-1.noarch.rpm state=present